### ISSUE TITLE
Fix missing timeouts in analysis-runner

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/analysis-runner#486]
Reenable `W3101` in `.pylintrc` (got disabled in https://github.com/populationgenomics/analysis-runner/pull/485) and add timeouts to `requests` calls (see https://github.com/populationgenomics/analysis-runner/runs/8064210784?check_suite_focus=true).

**Comment by illusional** [comment]
Pretty sure this was addressed, as the linting error is not there
