### ISSUE TITLE
DRIVER_IMAGE in conf

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/analysis-runner#562]
see: https://github.com/populationgenomics/analysis-runner/blob/5f6536ce7828bf06973333bcd7a1e366962f06ee/server/util.py#L187

When the analysis-runner driver image is overridden using `--image`, the 'driver_image' in the toml config is still the canonical driver image, with no option to override. The metadata for the job _does_ assign driverImage correctly.

Would it make sense that the image 'currently driving' the batch is persisted into config as the `driver`? I don't mind making the PR if we want to change the behaviour, but I wanted to check if this is intentional.

A use case I'm considering is that from the driver jobs, I expect `get_config()['workflow']['driver_image']` to provide the docker image which is currently being run. For non-default driver images this doesn't hold true.

**Comment by illusional** [comment]
I agree, IMO the driver-image should be overridden in the config. Happy to approve, or action later.

**Comment by lgruen** [comment]
Yes, I think this is just legacy from when we didn't have `--image` yet.
