### ISSUE TITLE
Unexpected CRAM 'output' values

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/analysis-runner#586]
[This line](https://github.com/populationgenomics/analysis-runner/blob/b2fd557081b2d14023c069e14a3fca4f55514024/scripts/copy_family_to_test.py#L92) causes a dodgy error - the CRAMs being registered are the Hail Batch Resource Group, not a single String. 

```
{
    ...
    'output': "{'cram': GSPath('gs://cpg-schr-neuro-main/cram/CPG261354.cram'), 'crai': GSPath('gs://cpg-schr-neuro-main/cram/CPG261354.cram.crai')}",
    ...
}
```

Identified during [this batch run](https://batch.hail.populationgenomics.org.au/batches/420940/jobs/1)

**Comment by cassimons** [comment]
As discussed in the seqr meeting today!

**Comment by illusional** [comment]
Hey @cassimons, as this will be addressed in the seqr audit, are you happy for me to assign this to @EddieLF?

**Comment by MattWellie** [comment]
Welp, this came back to haunt us 🥲
